# Generated by Django 5.2.3 on 2025-06-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование завода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Retail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование розничной сети"
                    ),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=150, verbose_name="Город")),
                ("street", models.CharField(max_length=150, verbose_name="Улица")),
                (
                    "building",
                    models.CharField(max_length=20, verbose_name="Номер дома"),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="Модель продукта"),
                ),
                ("product_date", models.DateField(verbose_name="Дата выхода")),
                ("debt", models.FloatField(default=0.0, verbose_name="Задолженность")),
                ("creation_date", models.DateField(verbose_name="Дата создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retail",
                        to="network.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розничная сеть",
                "verbose_name_plural": "Розничные сети",
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование завода"
                    ),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=150, verbose_name="Город")),
                ("street", models.CharField(max_length=150, verbose_name="Улица")),
                (
                    "building",
                    models.CharField(max_length=20, verbose_name="Номер дома"),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="Модель продукта"),
                ),
                ("product_date", models.DateField(verbose_name="Дата выхода")),
                ("debt", models.FloatField(default=0.0, verbose_name="Задолженность")),
                ("creation_date", models.DateField(verbose_name="Дата создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant",
                        to="network.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завод",
                "verbose_name_plural": "Заводы",
            },
        ),
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Наименование ИП"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=150, verbose_name="Город")),
                ("street", models.CharField(max_length=150, verbose_name="Улица")),
                (
                    "building",
                    models.CharField(max_length=20, verbose_name="Номер дома"),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="Модель продукта"),
                ),
                ("product_date", models.DateField(verbose_name="Дата выхода")),
                ("debt", models.FloatField(default=0.0, verbose_name="Задолженность")),
                ("creation_date", models.DateField(verbose_name="Дата создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrepreneur",
                        to="network.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный предприниматель",
                "verbose_name_plural": "Индивидуальные предприниматели",
            },
        ),
    ]
