# Generated by Django 5.2.3 on 2025-06-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=150, verbose_name="Город")),
                ("street", models.CharField(max_length=150, verbose_name="Улица")),
                (
                    "building",
                    models.CharField(max_length=20, verbose_name="Номер дома"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="Модель продукта"),
                ),
                ("product_date", models.DateField(verbose_name="Дата выхода")),
            ],
        ),
        migrations.RemoveField(
            model_name="plant",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="retail",
            name="supplier",
        ),
        migrations.CreateModel(
            name="NetworkLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("plant", "завод"),
                            ("retail", "розница"),
                            ("entrepreneur", "ип"),
                        ],
                        max_length=15,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Задолженность"
                    ),
                ),
                ("creation_date", models.DateField(verbose_name="Дата создания")),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="network.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_supplier",
                        to="network.networklink",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        to="network.product", verbose_name="Продукт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено",
                "verbose_name_plural": "Звенья",
            },
        ),
        migrations.DeleteModel(
            name="Entrepreneur",
        ),
        migrations.DeleteModel(
            name="Plant",
        ),
        migrations.DeleteModel(
            name="Retail",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
