# Generated by Django 5.2.3 on 2025-06-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_contact_product_remove_plant_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="network_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="NetworkLink",
                to="network.networklink",
                verbose_name="Звено",
            ),
        ),
    ]
